### PR TITLE
OCPCLOUD-1875,OCPBUGS-6465: Merge https://github.com/kubernetes-sigs/cluster-api-provider-vsphere:v1.7.0 (7e9205d) into master

### PR DESCRIPTION
**Pull request by damdo**

### CODE REVIEW

**Comment by damdo** [comment]
Happy with the results in `e2e-vsphere-serial`, as even if it failed it demonstrated that this rebase is not breaking the payload for `vsphere-serial`, where this component in the payload but not running in any capacity.
Hence overriding.
/override ci/prow/e2e-vsphere-serial

**Review by damdo — COMMENTED** [review]
/lgtm

**Comment by JoelSpeed** [comment]
/hold 

Some carry commits seem to be duplicated here, do you think we could drop these duplicates?

**Comment by damdo** [comment]
Now squashed @JoelSpeed

**Comment by odvarkadaniel** [comment]
Joel's comment is addressed.
/lgtm
/unhold

**Pull request merged**
